=== annrybakova/AirportManagment-Sql-connection/src/main/resources/xsd/booking.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified">

  <xs:element name="bookings">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="booking" type="BookingType" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="BookingType">
    <xs:sequence>
      <xs:element name="passengerId" type="xs:int"/>
      <xs:element name="flightId" type="xs:int"/>
      <xs:element name="bookingDate" type="xs:dateTime"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:int" use="required"/>
  </xs:complexType>

</xs:schema>

=== annrybakova/AirportManagment-Sql-connection/src/main/resources/xml/bookingXmlXsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<bookings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="../xsd/booking.xsd">

  <booking id="1">
    <passengerId>1</passengerId>
    <flightId>1</flightId>
    <bookingDate>2025-08-10T09:00:00</bookingDate>
  </booking>

  <booking id="2">
    <passengerId>2</passengerId>
    <flightId>1</flightId>
    <bookingDate>2025-08-10T09:05:00</bookingDate>
  </booking>

</bookings>
